name: Update Resume Gist

on:
  push:
    branches:
    - 'main'
    paths:
    - 'resume.json'

jobs:
  update-resume-gist:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '26'

    - name: Render Resume
      run: npx resumed render --theme jsonresume-theme-full-ext

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.gist_token }}
        gist_id: c08bff4ddd966ac26dd78070fd5b6ab8
        file_path: resume.json
